### PR TITLE
description update for API key and about page

### PR DESCRIPTION
**Pull request by mekaufman**

### CODE REVIEW

**Comment by mekaufman** [comment]
For the about page:

|Variable Name|Description|Default Value|
|-------------|-----------|-------------|
|region|Region to deploy VPC|us-east|
|ssh_public_key|Your public SSH key to access the virtual machine. Your public key is saved to a file called id_rsa.pub in the .ssh subdirectory of your home directory.||
|ssh_key_name|Name of SSH key|VPC_ssh_key|
|num_vms_per_VPC|Number of VMs to create per VPC|1|
|image|VM image identifier|7eb4e35b-4257-56f8-d7da-326d85452591|
|profile|VM CPU profile|b-2x8|

Can dev make improvements to any of the these deployment values:
1. Is there a command that can be run to get a list of regions to deploy VPC in? If so, let's add "Run the `command` to get a list of regions."
2. Where do they get the VM image identifier? Can we add that detail?
3. Where do they get the value for VM CPU profile? Can we add that detail?

Created an issue for the team on the above https://github.com/Cloud-Schematics/2-zone-vpc/issues/2

**Review by cdmauney — CHANGES_REQUESTED** [review]
The 2-Zone VPC template is an IBM Cloud Schematics template that is used to create two virtual private clouds (VPCs), each in a different zone.

**Review by cdmauney — CHANGES_REQUESTED** [review]
For more information about how to use this template, see the [IBM Cloud Schematics documentation](https://cloud.ibm.com/docs/schematics).

**Review by cdmauney — COMMENTED** [review]
Set the following variable before you use the template:

Your public key is saved to a `id_rsa.pub` file in the `.ssh` subdirectory of your home directory.

**Comment by cdmauney** [comment]
@mekaufman Review comments above.

**Pull request merged**
