### PR TITLE
descriptions for variables

### PR DESCRIPTION
**Pull request by mekaufman**
Whoever reviews and merges, can you add to this PR to improve the descriptions? 

1. Is there a command that can be run to get a list of regions to deploy VPC in? If so, let's add "Run the command to get a list of regions."

2. Where do they get the VM image identifier? Can you add that detail?

3. Where do they get the value for VM CPU profile? Can you add that detail?

### CODE REVIEW

**Comment by hkantare** [comment]
Is there a command that can be run to get a list of regions to deploy VPC in? If so, let's add "Run the command to get a list of regions."
**ic is regions -> will list supported regions**

Where do they get the VM image identifier? Can you add that detail?
**ic is images -> will list available images**

Where do they get the value for VM CPU profile? Can you add that detail?
**ic is instance-profiles -> will list available profiles**

**Comment by SaiKrishnaMohan7** [comment]
@hkantare is `ic is regions` common? It is not something aliased or anything? Should it `ic` be `ibmcloud`?

**Comment by hkantare** [comment]
yes ic is alias for ibmcloud...

**Comment by SaiKrishnaMohan7** [comment]
@hkantare I am thinking if this alias is set when a user installs ibmcloud cli

**Comment by hkantare** [comment]
Yes as per my knowledge the alias is set when you install ibmcloud cli..

**Pull request merged**
